---

- name: network2
  connection: network_cli
  hosts: all
  gather_facts: false
  tasks:
  - name: Check router onfig
    ios_banner:
      banner: login
      text: |
        'This is your new login messages'
      state: present
