---

- name: Setup new routers for ssh access
  hosts: all
  gather_facts: false
  connection: local
  tasks:
  - telnet:
      login_prompt: "Password: "
      password: cisco
      prompts:
      - "[>#]"
      command:
      - terminal length 0
      - show version
      - configure terminal
      - int lo
      - ip add 1.1.1.1 255.255.255.255
      - no shut
      - end
      - copy run start
