---

- name: Setup new routers for ssh access
  hosts: all
  gather_facts: false
  connection: local
  tasks:
  - telnet:
      login_prompt: "Password: "
      password: "{{ new_router_password }}"
      prompts:
      - "[>#]"
      command:
      - terminal length 0
      - show version
      - configure terminal
      - username ansible privilege 15 secret "{{ default_user_password }}"
      - line vty 0 4
      - transport input all
      - login local
      - exit
      - ip domain-name "{{ ip_domain_name }}"
      - exit
      - crypto key generate rsa
      - end
      - copy run start
