---

- name: Update lab-router inventory
  connection: network_cli
  hosts: all
  gather_facts: false
  tasks:
  - name: Get DHCP Bindings
    ios_command:
      commands: show ip dhcp bind | inc 01.*\.08
